# Generated by Django 4.1.4 on 2023-04-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrenamientosChirho',
            fields=[
                ('id_chirho', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombrecurso_chirho', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinariaEquipoChirho',
            fields=[
                ('id_chirho', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombre_chirho', models.CharField(max_length=50)),
                ('modelo_chirho', models.CharField(max_length=50)),
            ],
        ),
    ]
