# Generated by Django 4.1.4 on 2023-04-15 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('praind_chirho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamientoschirho',
            name='id_chirho',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrenamientoschirho',
            name='nombrecurso_chirho',
            field=models.CharField(max_length=50, verbose_name='Entrenamiento'),
        ),
        migrations.AlterField(
            model_name='maquinariaequipochirho',
            name='id_chirho',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
