# Generated by Django 4.1.4 on 2023-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praind_chirho', '0002_alter_entrenamientoschirho_id_chirho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinariaequipochirho',
            name='modelo_chirho',
            field=models.CharField(max_length=50, verbose_name='Modelo de equipo'),
        ),
        migrations.AlterField(
            model_name='maquinariaequipochirho',
            name='nombre_chirho',
            field=models.CharField(max_length=50, verbose_name='Nombre de equipo'),
        ),
    ]
